// src/components/MidImages.js
import midImage1 from './cards/card1.png';
import midImage2 from './cards/card2.png';
import midImage3 from './cards/card3.png';
import midImage4 from './cards/card4.png';
import midImage5 from './cards/card5.png';
import midImage6 from './cards/card6.png';
import midImage7 from './cards/card7.png';
import midImage8 from './cards/card8.png';
import midImage9 from './cards/card9.png';
import midImage10 from './cards/card10.png';
import midImage11 from './cards/card11.png';
import midImage12 from './cards/card12.png';
import midImage13 from './cards/card13.png';
import midImage14 from './cards/card14.png';
import midImage15 from './cards/card15.png';
import midImage16 from './cards/card16.png';
import midImage17 from './cards/card17.png';
import midImage18 from './cards/card18.png';
import midImage19 from './cards/card19.png';
import midImage20 from './cards/card20.png';
import midImage21 from './cards/card21.png';
import midImage22 from './cards/card22.png';
import midImage23 from './cards/card23.png';
import midImage24 from './cards/card24.png';
import midImage25 from './cards/card25.png';
import midImage26 from './cards/card26.png';
import midImage27 from './cards/card27.png';
import midImage28 from './cards/card28.png';
import midImage29 from './cards/card29.png';
import midImage30 from './cards/card30.png';
import midImage31 from './cards/card31.png';
import midImage32 from './cards/card32.png';
import midImage33 from './cards/card33.png';
import midImage34 from './cards/card34.png';
import midImage35 from './cards/card35.png';
import midImage36 from './cards/card36.png';
import midImage37 from './cards/card37.png';
import midImage38 from './cards/card38.png';
import midImage39 from './cards/card39.png';
import midImage40 from './cards/card40.png';
import midImage41 from './cards/card41.png';
import midImage42 from './cards/card42.png';
import midImage43 from './cards/card43.png';
import midImage44 from './cards/card44.png';
import midImage45 from './cards/card45.png';
import midImage46 from './cards/card46.png';
import midImage47 from './cards/card47.png';
import midImage48 from './cards/card48.png';
import midImage49 from './cards/card49.png';
// ... other mid images

const midImages = [midImage1, midImage2, midImage3, midImage4,midImage5, midImage6, midImage7, midImage8, midImage9, midImage10, midImage11, midImage12, midImage13, midImage14, midImage15, midImage16,midImage17, midImage18, midImage19, midImage20, midImage21, midImage22, midImage23, midImage24, midImage25, midImage26, midImage27, midImage28, midImage29, midImage30, midImage31, midImage32, midImage33, midImage34, midImage35, midImage36, midImage37, midImage38, midImage39, midImage40,midImage41, midImage42, midImage43, midImage44, midImage45, midImage46, midImage47, midImage48,midImage49];

export default midImages;
