// src/buttonImages.js
const buttonImages = [
    './stall1.png',
    './stall2.png',
    './stall3.png',
    './stall4.png',
    './stall5.png',
    './stall6.png',
    './stall7.png',
    './stall8.png',
    './stall9.png',
    './stall10.png',
    './stall11.png',
    './stall12.png',
    './stall13.png',
    './stall14.png',
    './stall15.png',
    './stall16.png',
    './stall17.png',
    './stall18.png',
    './stall19.png',
    './stall20.png',
    './stall21.png',
    './stall22.png',
    './stall23.png',
    './stall24.png',
    './stall25.png',
    './stall26.png',
    './stall27.png',
    './stall28.png',
    './stall29.png',
    './stall30.png',
    './stall31.png',
    './stall32.png',
    './stall33.png',
    './stall34.png',
    './stall35.png',
    './stall36.png',
    './stall37.png',
    './stall38.png',
    './stall39.png',
    './stall40.png',
    './stall41.png',
    './stall42.png',
    './stall43.png',
    './stall44.png',
    './stall45.png',
    './stall46.png',
    './stall47.png',
    './stall48.png',
    './stall49.png',

  ];
  
  export default buttonImages;
  